name: bioinfo
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - black
  - ruff
  - mypy
  - tox
  - structlog
  - pytest
  - pytest-snapshot
  - line_profiler
  - memory_profiler
  - mkdocs
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - openpyxl
  - python-dotenv
  - psycopg
  - sqlalchemy
  - sqlalchemy-utils
  - pandas
  - polars-lts-cpu
  - ibis-framework
  - seaborn
  - requests
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - optuna
  - hyperopt
  - pycaret
  - jupyterlab
  - ipywidgets
  - ipympl
  - ipytest
  - streamlit
  - pygwalker
  - pydantic
  - sqlmodel
  - alembic
  - sqlacodegen
  - pandera
  - rdkit
  - biopython
  - anndata
  - scanpy
  - r-base
  - r-essentials
  - r-rlang
  - r-tidyverse
  - r-wgcna
  - r-seurat
  - r-irkernel
  - r-biocmanager
  - bioconductor-biocgenerics
  - bioconductor-biocversion
  - bioconductor-biobase
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-monocle
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-org.dr.eg.db
  - bioconductor-org.rn.eg.db
  - bioconductor-mixomics
  - bioconductor-anndatar
